// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4O1b0m-InBm762qdsNLdkEfSNiyDRtrY',
    appId: '1:1042407728857:web:9636281bea8f2098b580c8',
    messagingSenderId: '1042407728857',
    projectId: 'movie-peggy-awesome',
    authDomain: 'movie-peggy-awesome.firebaseapp.com',
    storageBucket: 'movie-peggy-awesome.firebasestorage.app',
    measurementId: 'G-J5WVSY1NLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC91Cdk7FQLs2w6TJB5v5dxfgbU5k9GLFM',
    appId: '1:1042407728857:android:02cfde83f46a6d01b580c8',
    messagingSenderId: '1042407728857',
    projectId: 'movie-peggy-awesome',
    storageBucket: 'movie-peggy-awesome.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZnENKthTINn00_04GtsbI0rhh0innYYo',
    appId: '1:1042407728857:ios:bc43f346336575ebb580c8',
    messagingSenderId: '1042407728857',
    projectId: 'movie-peggy-awesome',
    storageBucket: 'movie-peggy-awesome.firebasestorage.app',
    iosBundleId: 'com.example.cina',
  );

}